{{- if and .Values.webhooksServer.enabled .Values.rbac.installClusterRoleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orray-webhooks-server
  labels:
    {{- include "orray.labels" . | nindent 4 }}
    {{- include "orray.webhooksServer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orray-webhooks-server
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: orray-webhooks-server
{{- end }}
