{{- if .Values.webhooksServer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: orray-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orray.labels" . | nindent 4 }}
    {{- include "orray.webhooksServer.labels" . | nindent 4 }}
data:
  ORRAY_NAMESPACE: {{ .Release.Namespace }}
  LOG_LEVEL: {{ quote .Values.webhooksServer.logLevel }}
  LOG_FORMAT: {{ quote .Values.webhooksServer.logFormat }}
{{- end }}
