{{- if .Values.webhooksServer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orray-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orray.labels" . | nindent 4 }}
    {{- include "orray.webhooksServer.labels" . | nindent 4 }}
{{- end }}
