{{- if .Values.webhooksServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orray-webhooks-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orray.labels" . | nindent 4 }}
    {{- include "orray.webhooksServer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "orray.selectorLabels" . | nindent 4 }}
    {{- include "orray.webhooksServer.labels" . | nindent 4 }}
{{- end }}
