{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orray-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orray.labels" . | nindent 4 }}
    {{- include "orray.controller.labels" . | nindent 4 }}
{{- end }}
