{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orrey-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orrey.labels" . | nindent 4 }}
    {{- include "orrey.controller.labels" . | nindent 4 }}
{{- end }}
