{{- if and .Values.webhooksServer.enabled .Values.webhooksServer.tls.selfSignedCert }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: orray-selfsigned-cert-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
