## @section Image Parameters
image:
  ## @param image.repository Image repository of orray
  repository: ghcr.io/orray-proj/orray
  ## @param image.tag Overrides the image tag. The default tag is the value of `.Chart.AppVersion`
  tag: ""
  ## @param image.pullPolicy Image pull policy
  pullPolicy: IfNotPresent
  ## @param image.pullSecrets List of imagePullSecrets.
  pullSecrets: []

## @section CRDs
crds:
  ## @param crds.install Indicates if Custom Resource Definitions should be installed and upgraded as part of the release. If set to `false`, the CRDs will only be installed if they do not already exist.
  install: true
  ## @param crds.keep Indicates if Custom Resource Definitions should be kept when a release is uninstalled.
  keep: true

## @section Global Parameters
global:
  ## @param global.env Environment variables to add to all orray pods.
  env: []
  #  - name: ENV_NAME
  #    value: value
  ## @param global.envFrom Environment variables to add to all orray pods from ConfigMaps or Secrets.
  envFrom: []
  #  - configMapRef:
  #      name: config-map-name
  #  - secretRef:
  #      name: secret-name
  ## @param global.nodeSelector Default node selector for all orray pods.
  nodeSelector: {}

  ## @param global.labels Labels to add to all resources.
  labels: {}
  ## @param global.annotations Annotations to add to all resources.
  annotations: {}
  ## @param global.podLabels Labels to add to all pods.
  podLabels: {}
  ## @param global.podAnnotations Annotations to add to pods.
  podAnnotations: {}

  ## @param global.tolerations Default tolerations for all orray pods.
  tolerations: []
  ## @param global.affinity Default affinity for all orray pods.
  affinity: {}
  ## @param global.securityContext Default security context for all orray pods.
  securityContext: {}

## @section Controller
## All settings for the controller component
controller:
  ## @param controller.enabled Whether the controller is enabled.
  enabled: true

  ## @param controller.labels Labels to add to the api resources. Merges with `global.labels`, allowing you to override or add to the global labels.
  labels: {}
  ## @param controller.annotations Annotations to add to the api resources. Merges with `global.annotations`, allowing you to override or add to the global annotations.
  annotations: {}
  ## @param controller.podLabels Optional labels to add to pods. Merges with `global.podLabels`, allowing you to override or add to the global labels.
  podLabels: {}
  ## @param controller.podAnnotations Optional annotations to add to pods. Merges with `global.podAnnotations`, allowing you to override or add to the global annotations.
  podAnnotations: {}

  ## All settings relating to the service account for the controller
  serviceAccount:
    ## @param controller.serviceAccount.clusterWideSecretReadingEnabled Specifies whether the controller's ServiceAccount should be granted read permissions to Secrets CLUSTER-WIDE in the orray control plane's cluster.
    clusterWideSecretReadingEnabled: true
  ## Reconciler-specific settings
  reconcilers:
    ## @param controller.reconcilers.maxConcurrentReconciles specifies the maximum number of resources EACH of the controller's reconcilers can reconcile concurrently. This setting may also be overridden on a per-reconciler basis.
    maxConcurrentReconciles: 4

  ## @param controller.securityContext Security context for controller pods. Defaults to `global.securityContext`.
  securityContext: {}

  ## @param controller.logLevel The log level for the controller.
  logLevel: INFO

  ## @param controller.logFormat The log format for the controller. Available options: console, json. Defaults to 'console'.
  logFormat: console

  ## @param controller.resources Resources limits and requests for the controller containers.
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  ## @param controller.nodeSelector Node selector for controller pods. Defaults to `global.nodeSelector`.
  nodeSelector: {}
  ## @param controller.tolerations Tolerations for controller pods. Defaults to `global.tolerations`.
  tolerations: []
  ## @param controller.affinity Specifies pod affinity for controller pods. Defaults to `global.affinity`.
  affinity: {}
  ## @param controller.env Environment variables to add to controller pods.
  env: []
  #  - name: ENV_NAME
  #    value: value
  ## @param controller.envFrom Environment variables to add to controller pods from ConfigMaps or Secrets.
  envFrom: []
  #  - configMapRef:
  #      name: config-map-name
  #  - secretRef:
  #      name: secret-name

## @section RBAC
rbac:
  ## @param rbac.installClusterRoles Indicates if `ClusterRoles` should be installed.
  installClusterRoles: true
  ## @param rbac.installClusterRoleBindings Indicates if `ClusterRoleBindings` should be installed.
  installClusterRoleBindings: true

## @section Webhooks
webhooks:
  ## @param webhooks.register Whether to create `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` resources.
  register: true

## @section Webhooks Server
webhooksServer:
  ## @param webhooksServer.enabled Whether the webhooks server is enabled.
  enabled: true
  ## @param webhooksServer.replicas The number of webhooks server pods.
  replicas: 1
  ## @param webhooksServer.logLevel The log level for the webhooks server.
  logLevel: INFO

  ## @param webhooksServer.logFormat The log format for the webhooks server. Available options: console, json. Defaults to 'console'.
  logFormat: console

  ## @param webhooksServer.labels Labels to add to the api resources. Merges with `global.labels`, allowing you to override or add to the global labels.
  labels: {}
  ## @param webhooksServer.annotations Annotations to add to the api resources. Merges with `global.annotations`, allowing you to override or add to the global annotations.
  annotations: {}
  ## @param webhooksServer.podLabels Optional labels to add to pods. Merges with `global.podLabels`, allowing you to override or add to the global labels.
  podLabels: {}
  ## @param webhooksServer.podAnnotations Optional annotations to add to pods. Merges with `global.podAnnotations`, allowing you to override or add to the global annotations.
  podAnnotations: {}
  ## @param webhooksServer.resources Resources limits and requests for the webhooks server containers.

  tls:
    ## @param webhooksServer.tls.selfSignedCert  Whether to generate a self-signed certificate for the controller's built-in webhook server. If `true`, `cert-manager` CRDs **must** be present in the cluster. Orray will create and use its own namespaced issuer. If `false`, a cert secret named `orray-webhooks-server-cert` **must** be provided in the same namespace as Kargo. There is no provision for webhooks without TLS.
    selfSignedCert: true

  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## @param webhooksServer.nodeSelector Node selector for the webhooks server pods. Defaults to `global.nodeSelector`.
  nodeSelector: {}
  ## @param webhooksServer.tolerations Tolerations for the webhooks server pods. Defaults to `global.tolerations`.
  tolerations: []
  ## @param webhooksServer.affinity Specifies pod affinity for the webhooks server pods. Defaults to `global.affinity`.
  affinity: {}
  ## @param webhooksServer.securityContext Security context for webhooks server pods. Defaults to `global.securityContext`.
  securityContext: {}
  ## @param webhooksServer.env Environment variables to add to webhook server pods.
  env: []
  #  - name: ENV_NAME
  #    value: value
  ## @param webhooksServer.envFrom Environment variables to add to webhook server pods from ConfigMaps or Secrets.
  envFrom: []
  #  - configMapRef:
  #      name: config-map-name
  #  - secretRef:
  #      name: secret-name
